// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int64              `json:"id"`
	AccountHolderName string             `json:"account_holder_name"`
	Balance           int64              `json:"balance"`
	Currency          string             `json:"currency"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID        int64              `json:"id"`
	AccountID pgtype.Int8        `json:"account_id"`
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64              `json:"id"`
	FromAccountID pgtype.Int8        `json:"from_account_id"`
	ToAccountID   pgtype.Int8        `json:"to_account_id"`
	Ammount       int64              `json:"ammount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
